CREATE TABLE CHANGELOG (
  ID BIGINT NOT NULL,
  APPLIED_AT VARCHAR(25) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE t1 (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  name varchar(20) NOT NULL,
  type varchar(20) NOT NULL,
  ref_id bigint(20) NOT NULL,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE t2 (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  type varchar(20) NOT NULL,
  date int(11) NOT NULL,
  updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY (date,type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;